# permissions for end users to edit awsauthitems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsauthitem-editor-role
rules:
- apiGroups:
  - aws.maruina.k8s
  resources:
  - awsauthitems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.maruina.k8s
  resources:
  - awsauthitems/status
  verbs:
  - get
