apiVersion: aws.maruina.k8s/v1alpha1
kind: AWSAuthItem
metadata:
  name: invalid
spec:
  mapUsers:
    - userarn: this-is-long-enought-but-is-not-a-valid-arn
      username: admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::111122223333:user/ops-user
      username: ops-user
      groups:
        - system:masters
  mapRoles:
    - rolearn: xyz:aws:iam::111122223333:user/ops-user
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
